// Id, Name, Amount ($), Address, Contact Name
const firstNames = ["Alan", "Ada", "Bob", "Grace", "Jon", "Steve", "Frank"];

const lastNames = [
  "Jobs",
  "Wozniak",
  "Turing",
  "von Neumann",
  "Lovelace",
  "Hopper",
];

const streets = [
  "Kierkegaard",
  "Russell",
  "Camus",
  "Nietzsche",
  "Descartes",
  "Newton",
  "Poincaré",
  "Laplace",
  "Euler",
];
const streetEndings = ["St", "Ave", "Rd", "Way"];

const generateUniqueNameFunction = (firstNames, lastNames) => {
  return function () {
    const randomFirstNameIndex = Math.floor(Math.random() * firstNames.length);
    const randomLastNameIndex = Math.floor(Math.random() * lastNames.length);
    const firstName = firstNames[randomFirstNameIndex];
    const lastName = lastNames[randomLastNameIndex];

    return `${firstName} ${lastName}`;
  };
};

const generateName = generateUniqueNameFunction(firstNames, lastNames);

export const generateObjects = (n) => {
  const objects = [];
  for (let i = 0; i < n; i++) {
    const object = {
      id: i,
      name: `Deal ${i}`,
      address: `${Math.floor(Math.random() * 1000) + 1} ${
        streets[Math.floor(Math.random() * streets.length)]
      } ${streetEndings[Math.floor(Math.random() * streetEndings.length)]}`,
      contactName: generateName(),
      amount: Math.random() * 100,
      email: `contact${i}@example.com`,
    };
    objects.push(object);
  }
  return objects;
};

export const data = [
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 3,
    name: "x deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 4,
    name: "ac deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 5,
    name: "b deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
  {
    id: 0,
    name: "xyz deal",
    address: "123 main street",
    contactName: "John Doe",
    amount: 30.45,
    email: "john@example.com",
  },
  {
    id: 1,
    name: "abc deal",
    address: "124 main street",
    contactName: "Jane Smith",
    amount: 25.3,
    email: "jane@example.com",
  },
  {
    id: 2,
    name: "ncf deal",
    address: "125 main street",
    contactName: "Bob Johnson",
    amount: 40.12,
    email: "bob@example.com",
  },
];
